#space <- rbind(c(0.025*0.99, 0.025*1.01), c(0.99*0.99, 0.99*1.01), c(2*0.99, 2*1.01), c(0.3*1, 1*0.3), c(1*0.95, 1*0.95))
#test <- model_data(model = demo_model, param_space = space, sample_number = 5, runs = 10, T = 50)


#' VAR_model
#'
#'VAR estimation based on model data
#'
#' @param var_select select the variables to be compared to the real world SVAR.
#' @param model_data list of list of dataframes generated by the model.
#' @param trim the number of observation to trim from the data set from 0 - trim
#' @param lag_select Integer for the lag order (default is p=1).
#' @param season Inlusion of centered seasonal dummy variables (integer value of frequency).
#' @param exog Inlusion of exogenous variables.
#' @param type Type of deterministic regressors to include.
#'
#' @return
#' @export
#'
#' @examples
VAR_model <- function(var_select, model_data, trim, lag_select, season = NULL, exog = NULL, type = 'const'){
 library(vars)

  #trim first obs
  model_data <-lapply(model_data[!is.na(model_data)], function(x){
    lapply(x, function(y){
      y <- y[,trim:ncol(y)] #trim the data
      y <- ts(t(y))[,var_select] #select variables
      VAR(y, p = lag_select, season = season, exog = exog, type = type) #estimate VAR residuals

    })
  })
 return(model_data)
}


#' VAR__emp
#'
#' VAR estimation based on empirical data
#'
#' @param data Empirical data to be used
#' @param var_select Variables to be compared to the model SVAR
#' @param lag_select Integer for the lag order (default is p=1).
#' @param season Inlusion of centered seasonal dummy variables (integer value of frequency).
#' @param exog Inlusion of exogenous variables.
#' @param type Type of deterministic regressors to include.
#'
#' @return
#' @export
#'
#' @examples
VAR_emp <- function(data, var_select, lag_select, season = NULL, exog = NULL, type = 'const'){
  data <- data[,var_select]
  y <- VAR(data, p = lag_select, season = season, exog = exog, type = type)
  return(y)
}

#test <- VAR_resid_data(data = Philippine_SVAR, var_select = c('Output.Gap', 'RRP'), lag_select = 2, season = NULL, exog = NULL, type = 'const' )


