#' VAR_model
#'
#'VAR estimation based on model data
#'
#' @param var_select select the variables to be compared to the real world SVAR.
#' @param model_data list of list of dataframes generated by the model.
#' @param trim the number of observation to trim from the data set from 0 - trim
#' @param lag_select Integer for the lag order (default is p=1).
#' @param season Inlusion of centered seasonal dummy variables (integer value of frequency).
#' @param exog Inlusion of exogenous variables.
#' @param type Type of deterministic regressors to include.
#'
#' @return
#' @export
#'
#' @examples
#'

VAR_model <- function(var_select, model_data, trim, lag_select, season = NULL, exog = NULL, type = 'const'){
 library(vars)
  #trim first obs
 lapply(model_data[!is.na(model_data)], function(x){
    lapply(x, function(y){
        y <- y %>%
          dplyr::select(!!var_select) %>%
          slice((trim+1):n()) %>%
          ts()

     infocrit<-VARselect(y, lag.max=6, type=type)
     lag<-infocrit$selection["AIC(n)"]
     VAR(y, p = lag, season = season, exog = exog, type = type) #estimate VAR residuals

    })
  })

}


#' VAR__emp
#'
#' VAR estimation based on empirical data
#'
#' @param data Empirical data to be used
#' @param var_select Variables to be compared to the model SVAR
#' @param lag_select Integer for the lag order (default is p=1).
#' @param season Inlusion of centered seasonal dummy variables (integer value of frequency).
#' @param exog Inlusion of exogenous variables.
#' @param type Type of deterministic regressors to include.
#'
#' @return
#' @export
#'
#' @examples
VAR_emp <- function(data, var_select, lag_select, season = NULL, exog = NULL, type = 'const'){
  data <- data %>%
    dplyr::select(all_of(var_select))

  infocrit<-VARselect(data, lag.max=6, type="const")
  lag<-infocrit$selection["AIC(n)"]
  y <- VAR(data, p = lag, season = season, exog = exog, type = type)
  return(y)
}

