#' VAR of model data
#'
#'VAR estimation where the input is a list of list of dataframes, where each dataframe represents a specific combination of a parameter setting and a simulation run.
#'
#' @param var_select Select the variables to be compared to the real world SVAR.
#' @param model_data List of list of dataframes generated by the model.
#' @param trim The number of observation to trim from the data set from 0 - trim.
#' @param lag_select Integer for the lag order. The default is NULL in which case the optimum lag is determined based on the AIC.
#' @inheritDotParams vars::VARselect -y
#' @inheritDotParams vars::VAR -y -p
#'
#' @return A list of list of VAR estimations.
#'
#'
#' @export
VAR_model <- function(var_select, model_data, trim, lag_select = NULL, ...){
  #trim first obs
 lapply(model_data[!is.na(model_data)], function(x){
    lapply(x, function(y){
        y <- y %>%
          dplyr::select(!!var_select) %>%
          slice((trim+1):n()) %>%
          ts()

     infocrit<-VARselect(y,  ...)
     if(is.null(lag_select)){
       lag<-infocrit$selection["AIC(n)"]
     } else{
       lag <- lag_select
     }

     VAR(y, p = lag,  ...) #estimate VAR residuals

    })
  })

}


#' VAR of empirical data
#'
#' VAR estimation based on empirical data
#'
#' @param data Empirical data to be used.
#' @param var_select Variables to be compared to the model SVAR.
#' @param lag_select Integer for the lag order. The default is NULL in which case the optimum lag is determined based on the information criterion.
#' @inheritDotParams vars::VARselect -y
#' @inheritDotParams vars::VAR -y -p
#'
#' @return A var estimation object.
#'
#' @export
VAR_emp <- function(data, var_select, lag_select = NULL, ...){
  data <- data %>%
    dplyr::select(all_of(var_select))

  infocrit<-VARselect(data, ...)
  if(is.null(lag_select)){
    lag<-infocrit$selection["AIC(n)"]
  } else{
    lag <- lag_select
  }
  y <- VAR(data, p = lag,  ...)
  return(y)
}

